name: generate ascii
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v6

        - name: install cowsay
          run: sudo apt-get install cowsay -y

        - name : execute cowsay command
          run: cowsay -f dragon "I m a dragon" >> dragon.txt

        - name: Check if file exists
          run: grep -i "dragon" dragon.txt

        - name: Read the file
          run: cat dragon.txt

        - name: list the files
          run: ls -ltrh