name: execute multiple job
on: push
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay
          run: sudo apt-get install cowsay -y
        
        - name: Generate dragon.txt
          run: cowsay -f dragon "I m dragon" >> dragon.txt
    
    test_job:
        runs-on: ubuntu-latest
        steps:
        - name: check if file exists
          run: grep -i "dragon" dragon.txt

    deploy_job:
        runs-on: ubuntu-latest
        steps:
        - name: read the file
          run: cat dragon.txt